### ISSUE TITLE
User Story: Store shared static data in python data structures rather than in the database

### ISSUE THREAD

**Issue by werwty** [project-koku/koku#1394]
## User Story

As a developer, I would like to be able to add and edit shared data without having to create a database migration.

Currently, there are many cases in Koku where shared static data is stored in JSON files and loaded into the database via migrations.
I believe these are due to the fact that koku and masu used to be separate applications and could only access these from the database.

However, with the masu/koku merger, we should reconsider and make these into python objects (see https://github.com/project-koku/koku/blob/master/koku/masu/celery/export.py#L6 as an example).
As python objects, these would be more transparent to update/read.

Some examples of where this occurs:

- [x] [Sub-Task 1934](https://github.com/project-koku/koku/issues/1934) - Store shared static data in python data structures rather than in the database for 0029_cloud_account_seeder.py
    - [x] [Sub-Task 2004](https://github.com/project-koku/koku/issues/2004) - Cloud Accounts store in a python constant instead of JSON (Revisit Python/JSON structure for consistency)
- [ ] [Sub-Task 1913](https://github.com/project-koku/koku/issues/1913) - Store shared static data in python data structures rather than in the database for 0018_auto_20190923_1838.py
- [x] [Sub-Task 1914](https://github.com/project-koku/koku/issues/1914) - Store shared static data in python data structures rather than in the database for 0010_costmodelmetricsmap.py
    - [x] [Bug introduced by 1914 solutions](https://github.com/project-koku/koku/issues/2016) - ProgrammingError: relation "cost_models_metrics_map" does not exist

## Impacts
API

## Assumptions

- Making these changes should not impact the API in any way.

## Acceptance Criteria

- [x] Database tables {cost_models_metrics_map, api_cloudaccount, reporting_common_reportcolumnmap, ...} storing these common objects are removed.
- [x] cloud account settings are loaded by a non-db migration mechanism
- [x] All API calls still work as before and conform to platform API response guidelines

**Comment by nbon12** [comment]
@werwty is the link in your description still pointing to the correct code? https://github.com/project-koku/koku/blob/master/koku/masu/celery/export.py#L6

**Comment by nbon12** [comment]
Planning and Estimation:

- I plan to delete the database seeder for cloud_account.
- I plan to store the following JSON into a .json file into a new directory /koku/api/cloud_accounts/data/cloud_accounts.json

```
[
    {
        "name" : "AWS Account ID",
        "value" : "589173575009"
    }
]
```
- I plan to return this JSON straight through the API, changing the formatting to match the current formatted JSON response. The cloud_account Model will be deleted. The cloud_account View will be changed to handle raw JSON. The cloud_account seeder will be deleted. The cloud_account tests will be altered to account for raw json instead of a database item.
- I estimate this to take 5 days. Any changes to this plan may change the estimate.
- After a PR is initially submitted and review begins, any additional review comment that requests for additional changes to be made will take an estimated 1 day per each request for additional change.

CC: @kholdaway @jlalbertson 

A separate email is to be manually sent by @nbon12 to those CC above containing a link to this message.
