### ISSUE TITLE
Store shared static data in python data structures rather than in the database for 0018_auto_20190923_1838.py

### ISSUE THREAD

**Issue by kholdaway** [project-koku/koku#1913]
## Sub-Task

As a developer, I would like to be able to add and edit shared data without having to create a database migration.

Currently, there are many cases in Koku where shared static data is stored in JSON files and loaded into the database via migrations.
I believe these are due to the fact that koku and masu used to be separate applications and could only access these from the database.

However, with the masu/koku merger, we should reconsider and make these into python objects (see https://github.com/project-koku/koku/blob/master/koku/masu/celery/export.py#L6 as an example).
As python objects, these would be more transparent to update/read.

Some examples of where this occurs:
- https://github.com/project-koku/koku/tree/master/koku/reporting_common
    Reporting common loads in the data from a JSON file and uses that to populate the DB. This results in us rewriting the reload_mapping migration every time these JSON files are updated: https://github.com/project-koku/koku/blob/master/koku/reporting_common/migrations/0018_auto_20190923_1838.py

## Impacts
API

## Assumptions

- Making these changes should not impact the API in any way.

## Acceptance Criteria

- [ ] Database tables {cost_models_metrics_map, api_cloudaccount, reporting_common_reportcolumnmap, ...} storing these common objects are removed.
- [ ] cloud account settings are environment variable driven
- [ ] Shared data is put into some common package.
- [ ] All API calls still work as before.

**Comment by nbon12** [comment]
Planning and Estimation:

- I plan to move the JSON in this directory: https://github.com/project-koku/koku/tree/master/koku/reporting_common/data into a tuple constant in the __init__.py here: https://github.com/project-koku/koku/blob/master/koku/reporting_common/__init__.py
- The tuple will contain all of the JSON in a single constant of the following format

```
REPORT_COLUMN_MAP = (
    {
        "database_column":"billing_resource",
        "database_table":"reporting_awscostentrybill",
        "provider_column_name":"bill/BillingEntity",
        "report_type":"AWS-CUR",
        "provider_type":"AWS"
    },
    ...
        {
        "database_column": "instance_id",
        "database_table": "reporting_azurecostentryproductservice",
        "provider_column_name": "InstanceId",
        "report_type": "AZURE-CUR",
        "provider_type": "AZURE"
    },
}
```
Note that this single constant contains all provider_types, this is a change from the original JSON that had multiple files for each provider.

- The reload data functions in these migration will be edited to do `pass`:  https://github.com/project-koku/koku/blob/master/koku/reporting_common/migrations/0001_initial_squashed_0007_auto_20190208_0316_squashed_0019_auto_20191022_1602.py#L16 
https://github.com/project-koku/koku/blob/master/koku/api/migrations/0014_reload_azure_map.py#L11

- This line will get data from the constant instead of the database: https://github.com/project-koku/koku/blob/master/koku/masu/database/reporting_common_db_accessor.py#L70

I estimate this to take 4 days. Review comments that block the PR to solve the solution differently may extend estimate this by 1 day per suggested change.
