### ISSUE TITLE
Store shared static data in python data structures rather than in the database for 0010_costmodelmetricsmap.py

### ISSUE THREAD

**Issue by kholdaway** [project-koku/koku#1914]
## Sub-Task

As a developer, I would like to be able to add and edit shared data without having to create a database migration.

Currently, there are many cases in Koku where shared static data is stored in JSON files and loaded into the database via migrations.
I believe these are due to the fact that koku and masu used to be separate applications and could only access these from the database.

However, with the masu/koku merger, we should reconsider and make these into python objects (see https://github.com/project-koku/koku/blob/master/koku/masu/celery/export.py#L6 as an example).
As python objects, these would be more transparent to update/read.

Some examples of where this occurs:
- https://github.com/project-koku/koku/blob/master/koku/api/migrations/0010_costmodelmetricsmap.py#L11
    Same as above.

## Impacts
API

## Assumptions

- Making these changes should not impact the API in any way.

## Acceptance Criteria

- [ ] Database tables {cost_models_metrics_map, api_cloudaccount, reporting_common_reportcolumnmap, ...} storing these common objects are removed.
- [ ] JSON settings are loaded by a non-db migration mechanism
- [ ] All API calls still work as before and conform to platform API response guidelines

**Comment by nbon12** [comment]
Planning and Estimation:

I plan to delete the area of code that inserts the cost model metrics map into the database.
I plan to load the cost model metrics map JSON directly into the View, and serve this View.
I plan to return this JSON straight through the API, changing the formatting to match the current formatted JSON response. 
I plan to alter the cost model metrics map tests to work without a database model and with a View.
I estimate this to take 5 days. Any changes to this plan may change the estimate.
After a PR is initially submitted and review begins, any additional review comment that requests for additional changes to be made will take an estimated 1 day per each request for additional change.

**Comment by nbon12** [comment]
Acceptance criteria: 

- Cost_models_metric_map currently performs querying based on source_type param. This new solution should also perform querying based on source_type param.
- The current Cost Models Metric Map performs a translation from OCP --> OpenShift Container Platform before returning the JSON to the client. This translation should also exist in the new solution.
