### ISSUE TITLE
Penetration Testing

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#2047]
## Summary
As a part of the run-up to GA, we need to have our security folks do penetration testing.

This epic will cover the stories involved in coordinating the testing effort.

Doc with additional details: https://docs.google.com/document/d/1pzLUNoGe_SbrNEGX5joLtkVKeQEEunFgTo23idsBFss/edit#heading=h.2cz3k5gpcpd0

Plan:
- [x] Deploy Koku to testing location
- [x] Validate Koku API is functioning
- [x] Validate Koku data ingestion is functioning
- [ ] Request product security team begin testing

**Comment by blentz** [comment]
Doc with notes about current status:

https://docs.google.com/document/d/1_zfMni1IK16SOGB-nS2jB_DKpcc5b3u5suB56RsK_AM/edit?usp=sharing
