### ISSUE TITLE
[Epic] Correlate cloud infrastructure costs to OKD costs

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#572]
## User Story
As a user of OKD in the cloud, I want to correlate my cloud infrastructure costs with my application resource needs so that I can understand what my per-application costs are.

This is an epic that includes the following high-level features:
1. Async ingestion of cloud provider price list
2. Add / Align cloud provider price list as Rate objects within customer Tenant.
3. Calculate a price-per-pod based on number of pods-per-node (discussion needed)
4. Indexing and summarization of calculations.

## Impacts
API, UI, Docs

## Assumptions
- Cloud provider has an accessible pricing API

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET/POST/PUT/PATCH/DELETE |
 | **Path** | /api/v1/?/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ] Cloud provider price lists are ingested (First target: AWS)
- [ ] per-cluster costs are calculated based on the instance size pricing obtained from cloud provider price list.
- [ ] per-pod costs are calculated based on per-cluster costs and observed cluster activity (number of pods running on the node within the report period) 
- [ ] API reports per-pod and per-node rates.
- [ ] API reports per-pod and per-node cost totals.
- [ ] (Stretch Goal) Cost calculations factor in possible cost-reductions (e.g. RIs) from cloud provider.
